<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CreateProduct\**" />
    <EmbeddedResource Remove="CreateProduct\**" />
    <None Remove="CreateProduct\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppStore.Entities\AppStore.Entities.csproj" />
    <ProjectReference Include="..\AppStore.Validation.Entities\AppStore.Validation.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\CreateProductMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CreateProductMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\CreateProductMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CreateProductMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
