//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Validators.Entities.Resources.Product.UpdateProduct {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateProductMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateProductMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStore.Validators.Entities.Resources.Product.UpdateProduct.UpdateProductMessage" +
                            "s", typeof(UpdateProductMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción no es válida..
        /// </summary>
        internal static string DescriptionInvalid {
            get {
                return ResourceManager.GetString("DescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripcion no debe superar los 500 digitos..
        /// </summary>
        internal static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripcion no puede contener solo espacios vacios..
        /// </summary>
        internal static string DescriptionOnlyWhitespace {
            get {
                return ResourceManager.GetString("DescriptionOnlyWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Id de la categoría debe ser mayor a 0..
        /// </summary>
        internal static string IdCategoryGreaterThanZero {
            get {
                return ResourceManager.GetString("IdCategoryGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Id del producto debe ser mayor a 0..
        /// </summary>
        internal static string IdProductGreaterThanZero {
            get {
                return ResourceManager.GetString("IdProductGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Id del proveedor debe ser mayor a 0..
        /// </summary>
        internal static string IdSupplierGreaterThanZero {
            get {
                return ResourceManager.GetString("IdSupplierGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código interno solo puede contener letras, números, guiones (-) o guiones bajos (_)..
        /// </summary>
        internal static string InternalCodeInvalidFormat {
            get {
                return ResourceManager.GetString("InternalCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código interno no debe superar los 50 dígitos..
        /// </summary>
        internal static string InternalCodeMaxLength {
            get {
                return ResourceManager.GetString("InternalCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código interno es obligatorio..
        /// </summary>
        internal static string InternalCodeRequired {
            get {
                return ResourceManager.GetString("InternalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no debe superar los 150 dígitos..
        /// </summary>
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio debe ser mayor a 0..
        /// </summary>
        internal static string PriceGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceGreaterThanZero", resourceCulture);
            }
        }
    }
}
