//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Validators.Entities.Resources.Product.CreateProduct {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateProductMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateProductMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStore.Validators.Entities.Resources.Product.CreateProduct.CreateProductMessage" +
                            "s", typeof(CreateProductMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción no puede superar los {0} caracteres..
        /// </summary>
        internal static string DescriptionMaximumLength {
            get {
                return ResourceManager.GetString("DescriptionMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripcion no puede contener solo espacios vacios..
        /// </summary>
        internal static string DescriptionOnlyWhitespace {
            get {
                return ResourceManager.GetString("DescriptionOnlyWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar una categoría válida..
        /// </summary>
        internal static string IdCategoryGreaterThanZero {
            get {
                return ResourceManager.GetString("IdCategoryGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar un proveedor válido..
        /// </summary>
        internal static string IdSupplierGreaterThanZero {
            get {
                return ResourceManager.GetString("IdSupplierGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código interno solo puede contener letras, números, guiones (-) o guiones bajos (_)..
        /// </summary>
        internal static string InternalCodeInvalidFormat {
            get {
                return ResourceManager.GetString("InternalCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código interno no puede superar los {0} caracteres..
        /// </summary>
        internal static string InternalCodeMaximumLength {
            get {
                return ResourceManager.GetString("InternalCodeMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar el código interno del producto..
        /// </summary>
        internal static string InternalCodeNotEmpty {
            get {
                return ResourceManager.GetString("InternalCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede superar los {0} caracteres..
        /// </summary>
        internal static string NameMaximumLength {
            get {
                return ResourceManager.GetString("NameMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar el nombre del producto..
        /// </summary>
        internal static string NameNotEmpty {
            get {
                return ResourceManager.GetString("NameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio debe ser mayor que cero..
        /// </summary>
        internal static string PriceGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad inicial no puede ser negativa..
        /// </summary>
        internal static string StockInitialGreaterOrEqualZero {
            get {
                return ResourceManager.GetString("StockInitialGreaterOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no puede superar 32.767..
        /// </summary>
        internal static string StockInitialLessOrEqualMaxValue {
            get {
                return ResourceManager.GetString("StockInitialLessOrEqualMaxValue", resourceCulture);
            }
        }
    }
}
