global using AppStore.Entities.DTOs.Products.CreateProduct;
global using AppStore.Frontend.BusinessObjects.Interfaces;
global using AppStore.Frontend.Views.Resources;
global using AppStore.Frontend.Views.ViewModels.CreateProduct;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using AppStore.Validation.Entities.Abstractions;
global using AppStore.Validation.Entities.Enums;
global using AppStore.Validation.Entities.Interfaces;
